spring:
  datasource:
    url: jdbc:mysql://120.55.60.114:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: _MALL(2UFxgq.
  elasticsearch:
    rest:
      uris: http://localhost:9200
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost