spring:
  datasource:
    url: jdbc:mysql://120.55.60.114:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: _MALL(2UFxgq.
  data:
    mongodb:
      host: 47.98.132.48
      port: 27017
      database: mall-port
      username: admin
      password: 123456
  redis:
    host: 120.55.60.114 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: 120.55.60.114
    port: 5672
    virtual-host: /mall
    username: guest
    password: guest
# 日志配置
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost